apiVersion: v1
kind: Service
metadata:
  name: PLACEHOLDER-APP-NAME
  labels:
    app: PLACEHOLDER-APP-NAME
    team: PLACEHOLDER-TEAM
    environment: PLACEHOLDER-ENVIRONMENT
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: PLACEHOLDER-APP-NAME
