apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference base templates from this repo (use actual version tag in production)
resources:
  - ../../base-deployment

# Set namespace for all resources
namespace: example-service

# Strategic merge patches to customize the deployment
patches:
  - target:
      kind: Deployment
      name: PLACEHOLDER-APP-NAME
    patch: |-
      - op: replace
        path: /metadata/name
        value: example-service
      - op: replace
        path: /spec/selector/matchLabels/app
        value: example-service
      - op: replace
        path: /spec/template/metadata/labels/app
        value: example-service
      - op: replace
        path: /spec/template/metadata/labels/team
        value: backend-team
      - op: replace
        path: /spec/template/metadata/labels/environment
        value: dev
      - op: replace
        path: /metadata/labels/app
        value: example-service
      - op: replace
        path: /metadata/labels/team
        value: backend-team
      - op: replace
        path: /metadata/labels/environment
        value: dev
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: example-service
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: myregistry.azurecr.io/example-service:v1.0.0
      - op: replace
        path: /spec/replicas
        value: 3

  - target:
      kind: Service
      name: PLACEHOLDER-APP-NAME
    patch: |-
      - op: replace
        path: /metadata/name
        value: example-service
      - op: replace
        path: /spec/selector/app
        value: example-service
      - op: replace
        path: /metadata/labels/app
        value: example-service
      - op: replace
        path: /metadata/labels/team
        value: backend-team
      - op: replace
        path: /metadata/labels/environment
        value: dev
